-- APPROVAL REQUIRED: project role creation and privileges.
-- No user assignments or parent-role assignments are included.
CREATE ROLE IF NOT EXISTS F1_INGESTOR;
CREATE ROLE IF NOT EXISTS F1_TRANSFORMER;
CREATE ROLE IF NOT EXISTS F1_BI_READER;

GRANT USAGE ON DATABASE F1_ANALYTICS TO ROLE F1_INGESTOR;
GRANT USAGE ON DATABASE F1_ANALYTICS TO ROLE F1_TRANSFORMER;
GRANT USAGE ON DATABASE F1_ANALYTICS TO ROLE F1_BI_READER;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE F1_INGESTOR;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE F1_TRANSFORMER;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE F1_BI_READER;

GRANT USAGE ON SCHEMA F1_ANALYTICS.RAW TO ROLE F1_INGESTOR;
GRANT CREATE TABLE ON SCHEMA F1_ANALYTICS.RAW TO ROLE F1_INGESTOR;
GRANT USAGE ON SCHEMA F1_ANALYTICS.AUDIT TO ROLE F1_INGESTOR;
GRANT CREATE TABLE ON SCHEMA F1_ANALYTICS.AUDIT TO ROLE F1_INGESTOR;

GRANT USAGE ON SCHEMA F1_ANALYTICS.RAW TO ROLE F1_TRANSFORMER;
GRANT SELECT ON ALL TABLES IN SCHEMA F1_ANALYTICS.RAW TO ROLE F1_TRANSFORMER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA F1_ANALYTICS.RAW TO ROLE F1_TRANSFORMER;
GRANT USAGE ON SCHEMA F1_ANALYTICS.STAGING TO ROLE F1_TRANSFORMER;
GRANT CREATE TABLE, CREATE VIEW ON SCHEMA F1_ANALYTICS.STAGING TO ROLE F1_TRANSFORMER;
GRANT USAGE ON SCHEMA F1_ANALYTICS.INTERMEDIATE TO ROLE F1_TRANSFORMER;
GRANT CREATE TABLE, CREATE VIEW ON SCHEMA F1_ANALYTICS.INTERMEDIATE TO ROLE F1_TRANSFORMER;
GRANT USAGE ON SCHEMA F1_ANALYTICS.MARTS TO ROLE F1_TRANSFORMER;
GRANT CREATE TABLE, CREATE VIEW ON SCHEMA F1_ANALYTICS.MARTS TO ROLE F1_TRANSFORMER;
GRANT USAGE ON SCHEMA F1_ANALYTICS.AUDIT TO ROLE F1_TRANSFORMER;
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA F1_ANALYTICS.AUDIT
    TO ROLE F1_TRANSFORMER;
GRANT SELECT, INSERT, UPDATE ON FUTURE TABLES IN SCHEMA F1_ANALYTICS.AUDIT
    TO ROLE F1_TRANSFORMER;

GRANT USAGE ON SCHEMA F1_ANALYTICS.MARTS TO ROLE F1_BI_READER;
GRANT SELECT ON ALL TABLES IN SCHEMA F1_ANALYTICS.MARTS TO ROLE F1_BI_READER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA F1_ANALYTICS.MARTS TO ROLE F1_BI_READER;
GRANT SELECT ON ALL VIEWS IN SCHEMA F1_ANALYTICS.MARTS TO ROLE F1_BI_READER;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA F1_ANALYTICS.MARTS TO ROLE F1_BI_READER;
