-- Execute as F1_INGESTOR. Existing objects and data are preserved.
CREATE TABLE IF NOT EXISTS F1_ANALYTICS.RAW.SOURCE_RECORDS (
    DATASET VARCHAR NOT NULL,
    BUSINESS_KEY VARCHAR NOT NULL,
    SEASON NUMBER(4,0) NOT NULL,
    ROUND_NUMBER NUMBER(3,0) NOT NULL,
    PAYLOAD VARIANT NOT NULL,
    PAYLOAD_HASH VARCHAR(64) NOT NULL,
    FIRST_INGESTED_AT TIMESTAMP_TZ NOT NULL,
    UPDATED_AT TIMESTAMP_TZ NOT NULL,
    RUN_ID VARCHAR NOT NULL
);
CREATE TABLE IF NOT EXISTS F1_ANALYTICS.AUDIT.INGESTION_RUNS (
    RUN_ID VARCHAR NOT NULL,
    DATASET VARCHAR NOT NULL,
    SEASON NUMBER(4,0) NOT NULL,
    ROUND_NUMBER NUMBER(3,0),
    ENDPOINT VARCHAR NOT NULL,
    STARTED_AT TIMESTAMP_TZ NOT NULL,
    COMPLETED_AT TIMESTAMP_TZ,
    STATUS VARCHAR NOT NULL,
    RECORDS_RECEIVED NUMBER,
    RECORDS_INSERTED NUMBER,
    RECORDS_UPDATED NUMBER,
    RECORDS_UNCHANGED NUMBER,
    RAW_COUNT NUMBER,
    ERROR_TYPE VARCHAR
);
