-- Execute as F1_INGESTOR; no user grants or warehouse changes.
CREATE TABLE IF NOT EXISTS F1_ANALYTICS.AUDIT.DAILY_RUNS (
    RUN_ID VARCHAR NOT NULL,
    STARTED_AT TIMESTAMP_TZ NOT NULL,
    COMPLETED_AT TIMESTAMP_TZ,
    STATUS VARCHAR NOT NULL,
    LOOKBACK_DAYS NUMBER NOT NULL,
    SUMMARY VARIANT,
    ERROR_TYPE VARCHAR
);
