-- Read-only checks; run as F1_INGESTOR or an authorized audit reader.
SELECT DATASET, SEASON, COUNT(*) AS ROW_COUNT,
       COUNT(DISTINCT BUSINESS_KEY) AS UNIQUE_KEYS,
       COUNT(DISTINCT ROUND_NUMBER) AS ROUNDS,
       MAX(UPDATED_AT) AS LAST_CHANGE
FROM F1_ANALYTICS.RAW.SOURCE_RECORDS
GROUP BY DATASET, SEASON
ORDER BY SEASON, DATASET;

SELECT DATASET, BUSINESS_KEY, COUNT(*) AS DUPLICATE_COUNT
FROM F1_ANALYTICS.RAW.SOURCE_RECORDS
GROUP BY DATASET, BUSINESS_KEY
HAVING COUNT(*) > 1;

SELECT RUN_ID, DATASET, SEASON, ROUND_NUMBER, STATUS,
       RECORDS_RECEIVED, RECORDS_INSERTED, RECORDS_UPDATED,
       RECORDS_UNCHANGED, RAW_COUNT, ERROR_TYPE,
       DATEDIFF('millisecond', STARTED_AT, COMPLETED_AT) / 1000.0 AS DURATION_SECONDS
FROM F1_ANALYTICS.AUDIT.INGESTION_RUNS
ORDER BY STARTED_AT DESC;
