-- Run as F1_INGESTOR. Content timestamps are not ingestion freshness timestamps.
SELECT RUN_ID, STARTED_AT, COMPLETED_AT, STATUS, LOOKBACK_DAYS, SUMMARY, ERROR_TYPE
FROM F1_ANALYTICS.AUDIT.DAILY_RUNS
ORDER BY STARTED_AT DESC LIMIT 20;

SELECT MAX(IFF(STATUS='SUCCESS', COMPLETED_AT, NULL)) AS LAST_SUCCESSFUL_INGESTION,
       DATEDIFF('hour', LAST_SUCCESSFUL_INGESTION, CURRENT_TIMESTAMP()) AS HOURS_SINCE_SUCCESS,
       IFF(LAST_SUCCESSFUL_INGESTION IS NULL OR HOURS_SINCE_SUCCESS > 36,
           'STALE', 'FRESH') AS INGESTION_FRESHNESS
FROM F1_ANALYTICS.AUDIT.DAILY_RUNS;

WITH latest AS (
    SELECT DATASET, SEASON, COALESCE(ROUND_NUMBER, 0) AS PARTITION_ROUND,
           STATUS, STARTED_AT, COMPLETED_AT,
           MAX(IFF(STATUS='SUCCESS', COMPLETED_AT, NULL)) OVER (
               PARTITION BY DATASET, SEASON, COALESCE(ROUND_NUMBER, 0)
           ) AS LAST_SUCCESSFUL_RUN
    FROM F1_ANALYTICS.AUDIT.INGESTION_RUNS
    QUALIFY ROW_NUMBER() OVER (
        PARTITION BY DATASET, SEASON, COALESCE(ROUND_NUMBER, 0)
        ORDER BY STARTED_AT DESC, RUN_ID DESC
    ) = 1
)
SELECT * FROM latest WHERE STATUS <> 'SUCCESS' ORDER BY STARTED_AT DESC;
